# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .azure_digital_twins_management_client import AzureDigitalTwinsManagementClient
from .version import VERSION

__all__ = ['AzureDigitalTwinsManagementClient']

__version__ = VERSION

